{
 "title": "ArgoCD / Operational / Overview",
 "description": "A dashboard that monitors ArgoCD with a focus on the operational side of ArgoCD. The dashboards were generated using [argo-cd-mixin](https://github.com/adinhodovic/argo-cd-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "ci/cd",
  "argo-cd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(argocd_app_info{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\"}, namespace)"
   },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "kubernetes_cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\"}, project)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "description": "The total number of Git repositories being monitored by ArgoCD.",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{\n  cluster=\"$cluster\",\n  namespace=~\"$namespace\",\n  job=~\"$job\"\n}) by (repo)\n",
     "legendFormat": "{{repo}}"
    },
    {}
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "The total number of clusters being managed by ArgoCD.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argocd_cluster_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(argocd_app_info) by (project))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "description": "The total number of applications being managed by ArgoCD.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "description": "A table listing all applications managed by ArgoCD, along with their health and sync statuses.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n) by (job, dest_server, project, name, health_status, sync_status)\n"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "piechart",
   "description": "The distribution of application health statuses managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n) by (health_status, name)\n",
     "legendFormat": "{{ health_status }} {{name}}"
    },
    {}
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "description": "The distribution of application sync statuses managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n) by (sync_status, name)\n",
     "legendFormat": "{{ sync_status}} {{name}}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "description": "A table listing all applications managed by ArgoCD, along with their health and sync statuses.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\" } ",
     "legendFormat": "{{dest_namespace}}__{{name}}__{{project}}__{{health_status}}__{{sync_status}}"
    }
   ]
  },
  { "title": "Sync Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "description": "A timeseries panel showing sync activity for applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, dest_server, project, name)\n> 0\n",
     "legendFormat": "{{ project }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "timeseries",
   "description": "A timeseries panel showing sync failures for applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\n        phase=~\"Error|Failed\"\n      }[$__rate_interval]\n    )\n  )\n) by (job, dest_server, project, name, phase)\n> 0\n",
     "legendFormat": "{{ project }}/{{ name }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"argocd\", container!=\"\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Container Restarts by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"${namespace}\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{\n  namespace=\"argocd\",\n  resource=\"cpu\"\n}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{\n  namespace=\"argocd\",\n  resource=\"cpu\"\n}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{\n  namespace=\"argocd\",\n  resource=\"memory\"\n}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{\n  namespace=\"argocd\",\n  resource=\"memory\"\n}) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{\n  namespace=\"argocd\",\n  container!=\"\",\n}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{\n  namespace=\"argocd\",\n  container!=\"\",\n}) by (container)"
    }
   ]
  },
  {
   "title": "OOM Events by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    container_oom_events_total{\n      namespace=\"argocd\",\n      pod=~\"argocd-.*\",\n      container!=\"\"\n    }[$__rate_interval]\n  )\n) by (container)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Reconciliation Activity",
   "type": "timeseries",
   "description": "A timeseries panel showing reconciliation activity for applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_reconcile_count{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n      }[$__rate_interval]\n    )\n  )\n) by (namespace, job)\n",
     "legendFormat": "{{ namespace }}/{{ job }}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "description": "A heatmap panel showing reconciliation performance for applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    argocd_app_reconcile_bucket{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n    }[$__rate_interval]\n  )\n) by (le)\n",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "timeseries",
   "description": "A timeseries panel showing Kubernetes API activity for applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_k8s_request_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, verb, resource_kind)\n",
     "legendFormat": "{{ verb }} {{ resource_kind }}"
    }
   ]
  },
  {
   "title": "Pending Kubectl Runs",
   "type": "timeseries",
   "description": "A timeseries panel showing pending kubectl runs for ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_kubectl_exec_pending{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n  }\n) by (job, command)\n",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Resource Objects",
   "type": "timeseries",
   "description": "A timeseries panel showing the number of resource objects in each cluster managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_cluster_api_resource_objects{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\n    server=~\"$kubernetes_cluster\"\n  }\n) by (namespace, job, server)\n",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "API Resources",
   "type": "timeseries",
   "description": "A timeseries panel showing the number of API resources in each cluster managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_cluster_api_resources{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n  }\n) by (namespace, job, server)\n",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "timeseries",
   "description": "A timeseries panel showing cluster events for clusters managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    argocd_cluster_events_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n\n    }[$__rate_interval]\n  )\n) by (namespace, job, server)\n",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Repo Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Git Requests (ls-remote)",
   "type": "timeseries",
   "description": "A timeseries panel showing git ls-remote requests made by ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    argocd_git_request_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\n      request_type=\"ls-remote\"\n    }[$__rate_interval]\n  )\n) by (namespace, job, repo)\n",
     "legendFormat": "{{ namespace }} - {{ repo }}"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "timeseries",
   "description": "A timeseries panel showing git checkout requests made by ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    argocd_git_request_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\n      request_type=\"fetch\"\n    }[$__rate_interval]\n  )\n) by (namespace, job, repo)\n",
     "legendFormat": "{{ namespace }} - {{ repo }}"
    }
   ]
  },
  {
   "title": "Git Fetch Performance",
   "type": "heatmap",
   "description": "A heatmap panel showing git fetch performance for ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    argocd_git_request_duration_seconds_bucket{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\n      request_type=\"fetch\"\n    }[$__rate_interval]\n  )\n) by (le)\n",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Git Ls-remote Performance",
   "type": "heatmap",
   "description": "A heatmap panel showing git ls-remote performance for ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    argocd_git_request_duration_seconds_bucket{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\n      request_type=\"ls-remote\"\n    }[$__rate_interval]\n  )\n) by (le)\n",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}