{
 "title": "ArgoCD-popular",
 "description": "Official ArgoCD Dashboard as of June 2021",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info, server)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  { "title": "Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(argocd_app_info) by (project))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Degraded apps",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{health_status=\"Degraded\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (sync_status, dest_namespace)",
     "legendFormat": "{{sync_status}} {{dest_namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Health Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (health_status) (\n  argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\"}\n)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  { "title": "Sync Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Sync Failures",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",phase=~\"Error|Failed\",dest_server=~\"$cluster\"}[$interval]))) by ($grouping, phase)",
     "legendFormat": "{{phase}}: {{$grouping}}"
    }
   ]
  },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval]))) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Reconciliation Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval])) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_k8s_request_total{namespace=~\"$namespace\",server=~\"$cluster\"}[$interval])) by (verb, resource_kind)",
     "legendFormat": "{{verb}} {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{namespace=~\"$namespace\",name=~\"app_.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pending kubectl run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_kubectl_exec_pending{namespace=~\"$namespace\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "Controller Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=~\"$namespace\",job=~\".*argocd.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Resource Objects Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_cluster_api_resource_objects{namespace=~\"$namespace\",server=~\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "API Resources Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "  sum(argocd_cluster_api_resources{namespace=~\"$namespace\",server=~\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Cluster Events Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_cluster_events_total{namespace=~\"$namespace\",server=~\"$cluster\"}[$interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Repo Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Git Requests (ls-remote)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Git Fetch Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\", namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Git Ls-Remote Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"ls-remote\", namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-repo-server\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"argocd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"argocd-server-metrics\", quantile=\"1\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 164 }, "options": { "content": "#### gRPC Services:" } },
  {
   "title": "ApplicationService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"application.ApplicationService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "ClusterService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"cluster.ClusterService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "ProjectService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"project.ProjectService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "RepositoryService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"repository.RepositoryService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SessionService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"session.SessionService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "VersionService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"version.VersionService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "AccountService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"account.AccountService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SettingsService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"settings.SettingsService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  { "title": "Redis Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "Requests by result",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 203 },
   "targets": [
    {
     "expr": "sum(increase(argocd_redis_request_total{namespace=~\"$namespace\"}[$interval])) by (failed)"
    }
   ]
  }
 ]
}