---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dataapp-project
  namespace: argocd
spec:
  destinations:
    - namespace: dataapp
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/RameezAhmedZaka/argocd-dataapp.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webapp-project
  namespace: argocd
spec:
  destinations:
    - namespace: webapp
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/RameezAhmedZaka/argocd-dataapp.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataapp-prod
  namespace: argocd
spec:
  project: dataapp-project
  source:
    repoURL: https://github.com/RameezAhmedZaka/argocd-dataapp.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: dataapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
spec:
  project: webapp-project
  source:
    repoURL: https://github.com/RameezAhmedZaka/argocd-dataapp.git
    targetRevision: HEAD
    path: overlays/webapp-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




